version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: IdentityModel
    versions:
    - 5.0.0
    - 5.0.1
    - 5.1.0
  - dependency-name: Microsoft.CodeDom.Providers.DotNetCompilerPlatform
    versions:
    - 3.6.0
  - dependency-name: Microsoft.Owin.Security.Jwt
    versions:
    - 4.1.1
  - dependency-name: Microsoft.IdentityModel.Protocols.WsFederation
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.8.0
    - 6.9.0
  - dependency-name: Microsoft.IdentityModel.JsonWebTokens
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.8.0
    - 6.9.0
  - dependency-name: Microsoft.IdentityModel.Logging
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.8.0
    - 6.9.0
  - dependency-name: Microsoft.IdentityModel.Tokens
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.8.0
    - 6.9.0
  - dependency-name: Microsoft.IdentityModel.Tokens.Saml
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.8.0
    - 6.9.0
  - dependency-name: Microsoft.Owin.Security.WsFederation
    versions:
    - 4.1.1
  - dependency-name: popper.js
    versions:
    - 1.16.1
